### ISSUE TITLE
Does vcc syntax check work on linux?

### ISSUE THREAD

**Issue by VicSch** [teared/VEX#11]
Hello,
your VEX add-on for ST3 is really great! Thank you for this!
Vcc syntax check works on Window machine as expected, but i can't force it works on Linux. When i hit Ctrl+B it throws this error:

> Exception in thread Thread-6:
> Traceback (most recent call last):
>   File "./python3.3/threading.py", line 901, in _bootstrap_inner
>   File "./python3.3/threading.py", line 858, in run
>   File "/home/victor/.config/sublime-text-3/Installed Packages/VEX.sublime-package/commands/vex_build.py", line 252, in worker
>     'characters': self.format_output(vcc),
>   File "/home/victor/.config/sublime-text-3/Installed Packages/VEX.sublime-package/commands/vex_build.py", line 335, in format_output
>     with open(file, encoding='utf-8') as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'vcc-bin'

The path to vcc inside .sublime-build settings file is:

> 

> "executable": "/opt/hfs18.0.599/bin/vcc",

What did I miss?

Victor.

**Comment by teared** [comment]
Hello @VicSch! Thank you for reporting. It might happen if you don't have this line in the .sublime-build file:
```
"vex_output": "stdout",
```
It is used to avoid writing the compiled vex files on disk.

Otherwise, it's either a bug in the way I work with temporary files, or the regular expression is too strict. Can you show me the sample output? Save the code below to a file called `test.vfl` and try to compile it directly:
```
"/opt/hfs18.0.599/bin/vcc" "path/to/this/test.vfl" --context cvex --vex-output stdout
```

This should normally print compiled vex code to the console:
```
#define foo 1
```
This will provide the message that I'd like to look at:
```
#define123 foo 1
```
Thanks!

**Comment by VicSch** [comment]
I've followed your instruction,  copy-past .sublime-build file and just changed path to vcc, therefore that line of code is in .sublime-build file.
And as you asked.
First vex code:

> ;_name	test
> ; ModuleID = 'test'
> 
> !context = !{!0}
> !version = !{!1}
> !precision = !{!2}
> 
> !0 = metadata !{metadata !"cvex"}
> !1 = metadata !{metadata !"18.0.599"}
> !2 = metadata !{metadata !"64"}
> 
> ;_code_end
> 

Second vex cod:

> /home/victor/Documents/test.vfl:1:1: Error 1057: Undefined directive "define123"

**Comment by teared** [comment]
Thank you, Victor. That's all I needed to know. I just pushed the new release, so the add-on will be updated via PaCo automatically. Cheers!

**Comment by VicSch** [comment]
I've updated up to 7.1.4 and it works now without any errors.
Thank you very much.
