### ISSUE TITLE
Can't compile if a struct is referenced.

### ISSUE THREAD

**Issue by indigosm** [teared/VEX#12]
I've got a .h file and it has a struct inside.    If i try to compile in sublime text, it gives this error:

Error 1088: Syntax error, unexpected struct.

I believe it's because houdini supposedly doesn't even let you put a struct inside a wrangler either, and so you must put the struct in a .h to get around that.  But I'm in the .h in sublime text so that defeats that trick.  I tried moving it to a different .h and then included it in this .h but it still has the same compile fail.  Any ways around this?  

Thanks in advance!
-seneca

**Comment by teared** [comment]
Hi! Sounds like you are on the right track! Have you tried build in the `As a Library` mode?

_Tools → Build With... → VEX Build — As a Library_

This is crucial, because the Wrangle script (wrapped Snippet VOP) is, essentially, a VEX function body: a block of statements between function's curly braces. Building VEX with `As a Snippet` mode wraps everything in a function!

**Comment by indigosm** [comment]
thank you so much!  that fixed it.  :)
