### ISSUE TITLE
Building to a snippet does not return the code to houdini.

### ISSUE THREAD

**Issue by FredrikLazer** [teared/VEX#14]
Is there a requirement on version for that? I might be overlooking something but I tried the setup on 2 machines so far and I cant get it to work.

**Comment by teared** [comment]
Hello @FredrikLazer!

To get your code back to Houdini, you need to save the file and close Sublime Text. Houdini will unfreeze and update from the file you just saved.

Building in Sublime Text is for checking syntax and getting compilation errors that you can navigate over and fix without closing the editor. Otherwise, you'd have to close Sublime Text, get the error in Houdini, remember it, and send the code back to the editor to fix it.
